### ISSUE TITLE
Suggestion: Only exit with non-zero status if there's a config error

### ISSUE THREAD

**Issue by rlnrln** [jribbens/sslexpiry#1]
We're running this as a CronJob within kubernetes. Exiting with a non-zero status will cause kubernetes to retry the job.

I suggest only exiting with a non-zero status if there's something wrong with the config file, or if one of the domains can't be reached. Even if it finds a problem with a domain, the program still fulfilled its purpose successfully.

Perhaps add a flag for strict mode, where warnings are treated as errors.

**Comment by jribbens** [comment]
Ok I've added a `--exit-zero` option that means it will always return a zero exit code unless an unhandled exception occurs.
